databases:
  - name: findnagasaki_DB
    databaseName: findnagasaki_db
    user: findnagasaki
    region: singapore

services:
  - type: web
    name: findnagasaki
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: findnagasaki_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

